import { heightToInches, type PlayerSeed } from "./types";

// Historical classes 2018-2023. Focused on high-pick, well-known prospects so
// the redraft / historical UX is rich. Summaries are original writeups.
export const PLAYERS_HISTORICAL: PlayerSeed[] = [
  // -------------------- 2023 --------------------
  {
    slug: "bryce-young",
    firstName: "Bryce", lastName: "Young",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Alabama", conference: "SEC", draftYear: 2023,
    heightInches: heightToInches(5, 10), weightLbs: 204,
    actualPick: 1, actualRound: 1, actualTeamAbbr: "CAR",
    summary: "Heisman-winning passer with elite feel and accuracy but a small frame that made him a polarizing QB1.",
    strengths: ["Anticipation", "Poise", "Accuracy to all levels"],
    weaknesses: ["Size", "Arm is average", "Durability projection"],
    nflComp: "Russell Wilson (early career)",
    grade: 8.4,
  },
  {
    slug: "cj-stroud",
    firstName: "C.J.", lastName: "Stroud",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Ohio State", conference: "Big Ten", draftYear: 2023,
    heightInches: heightToInches(6, 3), weightLbs: 214,
    actualPick: 2, actualRound: 1, actualTeamAbbr: "HOU",
    summary: "Pocket passer with plus arm, timing, and processing. Cleanest QB prospect in the class.",
    strengths: ["Pocket poise", "Timing and anticipation", "Layered accuracy"],
    weaknesses: ["Athletic creation off-script", "Deep-ball touch was up-and-down"],
    nflComp: "Matt Ryan",
    grade: 8.6,
  },
  {
    slug: "will-anderson-jr",
    firstName: "Will", lastName: "Anderson Jr.",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Alabama", conference: "SEC", draftYear: 2023,
    heightInches: heightToInches(6, 4), weightLbs: 253,
    actualPick: 3, actualRound: 1, actualTeamAbbr: "HOU",
    summary: "Complete edge prospect with elite motor, power, and rush plan. Premium every-down player.",
    strengths: ["Every-down impact", "Power", "Hand counters"],
    weaknesses: ["Average long speed", "Bend is good but not elite"],
    nflComp: "Khalil Mack",
    grade: 8.7,
  },
  {
    slug: "anthony-richardson",
    firstName: "Anthony", lastName: "Richardson",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Florida", conference: "SEC", draftYear: 2023,
    heightInches: heightToInches(6, 4), weightLbs: 244,
    actualPick: 4, actualRound: 1, actualTeamAbbr: "IND",
    summary: "Generational athlete at the position with a cannon arm. Accuracy and processing are long projects.",
    strengths: ["Athletic upside", "Arm strength", "Size"],
    weaknesses: ["Short-area accuracy", "Reads and processing", "Production at college level"],
    nflComp: "Cam Newton",
    grade: 8.0,
  },
  {
    slug: "devon-witherspoon",
    firstName: "Devon", lastName: "Witherspoon",
    position: "CB", positionGroup: "SECONDARY",
    school: "Illinois", conference: "Big Ten", draftYear: 2023,
    heightInches: heightToInches(6, 0), weightLbs: 181,
    actualPick: 5, actualRound: 1, actualTeamAbbr: "SEA",
    summary: "Physical, instinctive corner with elite run-support demeanor. Scheme-flex at multiple alignments.",
    strengths: ["Physicality", "Instincts", "Man coverage technique"],
    weaknesses: ["Slight frame", "Limited ball production early in career"],
    nflComp: "Jalen Ramsey (slighter)",
    grade: 8.4,
  },
  {
    slug: "paris-johnson-jr",
    firstName: "Paris", lastName: "Johnson Jr.",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Ohio State", conference: "Big Ten", draftYear: 2023,
    heightInches: heightToInches(6, 6), weightLbs: 313,
    actualPick: 6, actualRound: 1, actualTeamAbbr: "ARI",
    summary: "High ceiling LT with elite length and movement skills. Still refining technique on early tape.",
    strengths: ["Length", "Athletic profile", "Upside at LT"],
    weaknesses: ["Hand placement", "Anchor against power"],
    nflComp: "Trent Williams (lite)",
    grade: 8.2,
  },
  {
    slug: "bijan-robinson",
    firstName: "Bijan", lastName: "Robinson",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Texas", conference: "Big 12", draftYear: 2023,
    heightInches: heightToInches(5, 11), weightLbs: 215,
    actualPick: 8, actualRound: 1, actualTeamAbbr: "ATL",
    summary: "Three-down back with elite vision, creativity, and contact balance. RB1 in class by a wide margin.",
    strengths: ["Vision", "Contact balance", "Receiving profile"],
    weaknesses: ["Positional value limits draft-day ceiling", "Usage concerns"],
    nflComp: "Le'Veon Bell",
    grade: 8.6,
  },
  {
    slug: "jahmyr-gibbs",
    firstName: "Jahmyr", lastName: "Gibbs",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Alabama", conference: "SEC", draftYear: 2023,
    heightInches: heightToInches(5, 9), weightLbs: 199,
    actualPick: 12, actualRound: 1, actualTeamAbbr: "DET",
    summary: "Home-run hitter with elite receiving profile. Satellite weapon who also handled real RB workload.",
    strengths: ["Home-run speed", "Receiving profile", "Pass-pro willingness"],
    weaknesses: ["Size between the tackles", "Positional value"],
    nflComp: "Alvin Kamara",
    grade: 8.2,
  },

  // -------------------- 2022 --------------------
  {
    slug: "travon-walker",
    firstName: "Travon", lastName: "Walker",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Georgia", conference: "SEC", draftYear: 2022,
    heightInches: heightToInches(6, 5), weightLbs: 272,
    actualPick: 1, actualRound: 1, actualTeamAbbr: "JAX",
    summary: "Rare traits edge with elite length and explosion numbers. Pass-rush polish was the question.",
    strengths: ["Elite testing profile", "Length", "Power"],
    weaknesses: ["Limited college production", "Rush plan is raw"],
    nflComp: "Julius Peppers (less polished)",
    grade: 8.3,
  },
  {
    slug: "aidan-hutchinson",
    firstName: "Aidan", lastName: "Hutchinson",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Michigan", conference: "Big Ten", draftYear: 2022,
    heightInches: heightToInches(6, 7), weightLbs: 260,
    actualPick: 2, actualRound: 1, actualTeamAbbr: "DET",
    summary: "Technically refined edge with elite motor and a well-developed rush plan. Clean Day 1 starter.",
    strengths: ["Rush plan", "Motor", "Run defense"],
    weaknesses: ["Average bend", "Athletic ceiling is solid rather than elite"],
    nflComp: "J.J. Watt (lite)",
    grade: 8.6,
  },
  {
    slug: "ikem-ekwonu",
    firstName: "Ikem", lastName: "Ekwonu",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "NC State", conference: "ACC", draftYear: 2022,
    heightInches: heightToInches(6, 4), weightLbs: 310,
    actualPick: 6, actualRound: 1, actualTeamAbbr: "CAR",
    summary: "Powerful run-game mover with room to improve in pass protection. Mauler profile.",
    strengths: ["Run game", "Power", "Finishing mentality"],
    weaknesses: ["Pass-pro technique", "Recovery in open space"],
    nflComp: "Jawaan Taylor",
    grade: 8.0,
  },
  {
    slug: "sauce-gardner",
    firstName: "Ahmad", lastName: "Gardner",
    position: "CB", positionGroup: "SECONDARY",
    school: "Cincinnati", conference: "AAC", draftYear: 2022,
    heightInches: heightToInches(6, 3), weightLbs: 190,
    actualPick: 4, actualRound: 1, actualTeamAbbr: "NYJ",
    summary: "Long, smooth press corner with elite ball production. Did not allow a TD in college career.",
    strengths: ["Length and press feel", "Ball skills", "Competitive toughness"],
    weaknesses: ["Average tackling", "Occasional bail technique in off coverage"],
    nflComp: "Richard Sherman",
    grade: 8.7,
  },
  {
    slug: "derek-stingley-jr",
    firstName: "Derek", lastName: "Stingley Jr.",
    position: "CB", positionGroup: "SECONDARY",
    school: "LSU", conference: "SEC", draftYear: 2022,
    heightInches: heightToInches(6, 0), weightLbs: 190,
    actualPick: 3, actualRound: 1, actualTeamAbbr: "HOU",
    summary: "Elite true freshman tape, then injuries. Press man corner with ball skills.",
    strengths: ["Man coverage", "Ball skills", "Elite freshman tape"],
    weaknesses: ["Medical", "Inconsistent late college tape"],
    nflComp: "Patrick Peterson (slighter)",
    grade: 8.1,
  },
  {
    slug: "garrett-wilson",
    firstName: "Garrett", lastName: "Wilson",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Ohio State", conference: "Big Ten", draftYear: 2022,
    heightInches: heightToInches(6, 0), weightLbs: 183,
    actualPick: 10, actualRound: 1, actualTeamAbbr: "NYJ",
    summary: "Route technician with plus separation and body control. All-alignment WR.",
    strengths: ["Route detail", "Body control", "Separation"],
    weaknesses: ["Frame is slight", "Average play strength"],
    nflComp: "Stefon Diggs",
    grade: 8.3,
  },
  {
    slug: "chris-olave",
    firstName: "Chris", lastName: "Olave",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Ohio State", conference: "Big Ten", draftYear: 2022,
    heightInches: heightToInches(6, 0), weightLbs: 187,
    actualPick: 11, actualRound: 1, actualTeamAbbr: "NO",
    summary: "Smooth vertical threat with elite route detail and tracking. Clean WR1 ceiling.",
    strengths: ["Route running", "Tracking", "Separation"],
    weaknesses: ["Average play strength", "Contested catch"],
    nflComp: "Marvin Harrison Sr.",
    grade: 8.2,
  },
  {
    slug: "drake-london",
    firstName: "Drake", lastName: "London",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "USC", conference: "Pac-12", draftYear: 2022,
    heightInches: heightToInches(6, 4), weightLbs: 219,
    actualPick: 8, actualRound: 1, actualTeamAbbr: "ATL",
    summary: "Big-bodied WR with elite catch radius. Basketball background shows in contested catch.",
    strengths: ["Catch radius", "Body control", "YAC ability for size"],
    weaknesses: ["Did not run at combine (injury)", "Long-speed projection"],
    nflComp: "Mike Evans",
    grade: 8.1,
  },

  // -------------------- 2021 --------------------
  {
    slug: "trevor-lawrence",
    firstName: "Trevor", lastName: "Lawrence",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Clemson", conference: "ACC", draftYear: 2021,
    heightInches: heightToInches(6, 6), weightLbs: 220,
    actualPick: 1, actualRound: 1, actualTeamAbbr: "JAX",
    summary: "Consensus top-of-class franchise QB with size, arm, and accuracy.",
    strengths: ["Size and arm", "Accuracy", "Athleticism"],
    weaknesses: ["Turnover-worthy plays when pressing", "Deep-ball variance"],
    nflComp: "Andrew Luck",
    grade: 9.0,
  },
  {
    slug: "zach-wilson",
    firstName: "Zach", lastName: "Wilson",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "BYU", conference: "Independent", draftYear: 2021,
    heightInches: heightToInches(6, 2), weightLbs: 214,
    actualPick: 2, actualRound: 1, actualTeamAbbr: "NYJ",
    summary: "Highlight-heavy off-platform passer. Decision-making under NFL duress was the real question.",
    strengths: ["Off-platform arm", "Creation ability"],
    weaknesses: ["Reads", "Decision-making vs pressure"],
    grade: 7.6,
  },
  {
    slug: "jamaar-chase",
    firstName: "Ja'Marr", lastName: "Chase",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "LSU", conference: "SEC", draftYear: 2021,
    heightInches: heightToInches(6, 0), weightLbs: 201,
    actualPick: 5, actualRound: 1, actualTeamAbbr: "CIN",
    summary: "Complete receiver prospect with elite release package and ball skills. Sat out 2020 COVID season.",
    strengths: ["Releases vs press", "Ball skills", "YAC ability"],
    weaknesses: ["Did not play 2020 season", "Average route nuance early"],
    nflComp: "A.J. Green",
    grade: 8.8,
  },
  {
    slug: "kyle-pitts",
    firstName: "Kyle", lastName: "Pitts",
    position: "TE", positionGroup: "OFFENSE_SKILL",
    school: "Florida", conference: "SEC", draftYear: 2021,
    heightInches: heightToInches(6, 6), weightLbs: 245,
    actualPick: 4, actualRound: 1, actualTeamAbbr: "ATL",
    summary: "Unicorn tight end with WR-level route ability and elite catch radius.",
    strengths: ["Route running", "Catch radius", "Mismatch potential"],
    weaknesses: ["Inline blocking", "Play strength"],
    nflComp: "Vernon Davis",
    grade: 9.0,
  },
  {
    slug: "penei-sewell",
    firstName: "Penei", lastName: "Sewell",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Oregon", conference: "Pac-12", draftYear: 2021,
    heightInches: heightToInches(6, 5), weightLbs: 331,
    actualPick: 7, actualRound: 1, actualTeamAbbr: "DET",
    summary: "Elite movement skills at tackle with mauler run-game mentality.",
    strengths: ["Elite athlete for size", "Run game", "Anchor"],
    weaknesses: ["Opted out of 2020 season", "Footwork in pass pro needs reps"],
    nflComp: "Tyron Smith",
    grade: 8.9,
  },
  {
    slug: "micah-parsons",
    firstName: "Micah", lastName: "Parsons",
    position: "LB", positionGroup: "LINEBACKER",
    school: "Penn State", conference: "Big Ten", draftYear: 2021,
    heightInches: heightToInches(6, 3), weightLbs: 246,
    actualPick: 12, actualRound: 1, actualTeamAbbr: "DAL",
    summary: "Generational athlete with edge-rush flex. Projected as premium defender immediately.",
    strengths: ["Elite athlete", "Pass-rush upside", "Closing burst"],
    weaknesses: ["Coverage instincts were projection"],
    nflComp: "Von Miller",
    grade: 8.8,
  },

  // -------------------- 2020 --------------------
  {
    slug: "joe-burrow",
    firstName: "Joe", lastName: "Burrow",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "LSU", conference: "SEC", draftYear: 2020,
    heightInches: heightToInches(6, 3), weightLbs: 221,
    actualPick: 1, actualRound: 1, actualTeamAbbr: "CIN",
    summary: "Heisman and national champ QB with elite accuracy and poise. Floor-raiser for a franchise.",
    strengths: ["Accuracy", "Poise", "Ball placement"],
    weaknesses: ["Average arm strength", "Limited mobility"],
    nflComp: "Philip Rivers",
    grade: 8.8,
  },
  {
    slug: "chase-young",
    firstName: "Chase", lastName: "Young",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Ohio State", conference: "Big Ten", draftYear: 2020,
    heightInches: heightToInches(6, 5), weightLbs: 264,
    actualPick: 2, actualRound: 1, actualTeamAbbr: "WAS",
    summary: "Dominant edge rusher with power, bend, and plus plan. DE1 in class.",
    strengths: ["Power", "Bend", "Rush plan"],
    weaknesses: ["Injury history", "Average long speed"],
    nflComp: "DeMarcus Ware",
    grade: 8.8,
  },
  {
    slug: "tua-tagovailoa",
    firstName: "Tua", lastName: "Tagovailoa",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Alabama", conference: "SEC", draftYear: 2020,
    heightInches: heightToInches(6, 0), weightLbs: 217,
    actualPick: 5, actualRound: 1, actualTeamAbbr: "MIA",
    summary: "Accurate rhythm passer with natural ball placement. Durability history and arm strength were concerns.",
    strengths: ["Accuracy", "Rhythm", "Processing"],
    weaknesses: ["Durability", "Arm strength"],
    nflComp: "Drew Brees",
    grade: 8.3,
  },
  {
    slug: "justin-herbert",
    firstName: "Justin", lastName: "Herbert",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Oregon", conference: "Pac-12", draftYear: 2020,
    heightInches: heightToInches(6, 6), weightLbs: 236,
    actualPick: 6, actualRound: 1, actualTeamAbbr: "LAC",
    summary: "Prototype size-arm QB who was polarizing pre-draft. Tools were always elite.",
    strengths: ["Arm strength", "Size", "Athleticism"],
    weaknesses: ["Consistency of decision-making in college", "Leadership narrative pre-draft"],
    nflComp: "Carson Palmer",
    grade: 8.0,
  },
  {
    slug: "ceedee-lamb",
    firstName: "CeeDee", lastName: "Lamb",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Oklahoma", conference: "Big 12", draftYear: 2020,
    heightInches: heightToInches(6, 2), weightLbs: 198,
    actualPick: 17, actualRound: 1, actualTeamAbbr: "DAL",
    summary: "Complete WR with plus YAC, contested catch, and route ability.",
    strengths: ["YAC", "Body control", "Contested catch"],
    weaknesses: ["Not an elite separator vs press", "Average long speed"],
    nflComp: "Michael Thomas",
    grade: 8.4,
  },

  // -------------------- 2019 --------------------
  {
    slug: "kyler-murray",
    firstName: "Kyler", lastName: "Murray",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Oklahoma", conference: "Big 12", draftYear: 2019,
    heightInches: heightToInches(5, 10), weightLbs: 207,
    actualPick: 1, actualRound: 1, actualTeamAbbr: "ARI",
    summary: "Electric dual-threat QB with elite arm and legs. Size was the only real asterisk.",
    strengths: ["Arm strength", "Creation", "Rushing ability"],
    weaknesses: ["Size", "Processing in condensed areas"],
    nflComp: "Russell Wilson",
    grade: 8.6,
  },
  {
    slug: "nick-bosa",
    firstName: "Nick", lastName: "Bosa",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Ohio State", conference: "Big Ten", draftYear: 2019,
    heightInches: heightToInches(6, 4), weightLbs: 266,
    actualPick: 2, actualRound: 1, actualTeamAbbr: "SF",
    summary: "Polished edge with plus bend, hands, and rush plan. Premium Day 1 defender.",
    strengths: ["Bend", "Rush plan", "Motor"],
    weaknesses: ["Medical concern pre-draft", "Average long speed"],
    nflComp: "His brother Joey",
    grade: 9.1,
  },
  {
    slug: "quinnen-williams",
    firstName: "Quinnen", lastName: "Williams",
    position: "DT", positionGroup: "DEFENSIVE_LINE",
    school: "Alabama", conference: "SEC", draftYear: 2019,
    heightInches: heightToInches(6, 3), weightLbs: 303,
    actualPick: 3, actualRound: 1, actualTeamAbbr: "NYJ",
    summary: "Dominant interior player with quickness, hands, and motor.",
    strengths: ["First step", "Hand use", "Motor"],
    weaknesses: ["Positional value"],
    nflComp: "Gerald McCoy",
    grade: 8.8,
  },
  {
    slug: "josh-allen-edge",
    firstName: "Josh", lastName: "Allen",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Kentucky", conference: "SEC", draftYear: 2019,
    heightInches: heightToInches(6, 5), weightLbs: 262,
    actualPick: 7, actualRound: 1, actualTeamAbbr: "JAX",
    summary: "Long, explosive edge with plus motor and productive breakout senior year.",
    strengths: ["Length", "Explosion", "Motor"],
    weaknesses: ["One-year production", "Rush counters to be developed"],
    nflComp: "Jadeveon Clowney",
    grade: 8.4,
  },

  // -------------------- 2018 --------------------
  {
    slug: "saquon-barkley",
    firstName: "Saquon", lastName: "Barkley",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Penn State", conference: "Big Ten", draftYear: 2018,
    heightInches: heightToInches(6, 0), weightLbs: 233,
    actualPick: 2, actualRound: 1, actualTeamAbbr: "NYG",
    summary: "Generational RB traits with rare athletic profile at the position.",
    strengths: ["Athleticism", "Home-run speed", "Receiving"],
    weaknesses: ["Positional value", "Will dance at times instead of getting downhill"],
    nflComp: "Barry Sanders (modernized)",
    grade: 8.8,
  },
  {
    slug: "baker-mayfield",
    firstName: "Baker", lastName: "Mayfield",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Oklahoma", conference: "Big 12", draftYear: 2018,
    heightInches: heightToInches(6, 1), weightLbs: 215,
    actualPick: 1, actualRound: 1, actualTeamAbbr: "CLE",
    summary: "Heisman passer with plus accuracy and competitive fire. Size was the only real flag.",
    strengths: ["Accuracy", "Competitiveness", "Ball placement"],
    weaknesses: ["Height", "Hero-ball tendencies"],
    grade: 8.2,
  },
  {
    slug: "quenton-nelson",
    firstName: "Quenton", lastName: "Nelson",
    position: "IOL", positionGroup: "OFFENSIVE_LINE",
    school: "Notre Dame", conference: "Independent", draftYear: 2018,
    heightInches: heightToInches(6, 5), weightLbs: 329,
    actualPick: 6, actualRound: 1, actualTeamAbbr: "IND",
    summary: "Elite OG prospect. Power, finish, and technique with all-pro ceiling.",
    strengths: ["Power", "Finishing", "Pass-pro strength"],
    weaknesses: ["Position was not premium on board"],
    nflComp: "Larry Allen",
    grade: 9.0,
  },
  {
    slug: "josh-allen-qb",
    firstName: "Josh", lastName: "Allen",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Wyoming", conference: "Mountain West", draftYear: 2018,
    heightInches: heightToInches(6, 5), weightLbs: 237,
    actualPick: 7, actualRound: 1, actualTeamAbbr: "BUF",
    summary: "Tools-based QB with elite arm and athleticism at a big frame. Accuracy was the central question.",
    strengths: ["Elite arm", "Size", "Athleticism"],
    weaknesses: ["Accuracy and completion rate", "Level of competition"],
    nflComp: "Ben Roethlisberger",
    grade: 7.8,
  },
  {
    slug: "lamar-jackson",
    firstName: "Lamar", lastName: "Jackson",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Louisville", conference: "ACC", draftYear: 2018,
    heightInches: heightToInches(6, 2), weightLbs: 216,
    actualPick: 32, actualRound: 1, actualTeamAbbr: "BAL",
    summary: "Heisman dual-threat with elite athletic tools. Passing accuracy was underrated coming out.",
    strengths: ["Rushing impact", "Arm talent", "Competitiveness"],
    weaknesses: ["Short-area accuracy pre-draft", "Passing operation timing was a projection"],
    nflComp: "Michael Vick (better thrower)",
    grade: 7.9,
  },
  {
    slug: "derwin-james",
    firstName: "Derwin", lastName: "James",
    position: "S", positionGroup: "SECONDARY",
    school: "Florida State", conference: "ACC", draftYear: 2018,
    heightInches: heightToInches(6, 2), weightLbs: 215,
    actualPick: 17, actualRound: 1, actualTeamAbbr: "LAC",
    summary: "Do-everything safety. Box, slot, deep, pass rush. Rare chess piece.",
    strengths: ["Versatility", "Athleticism", "Physicality"],
    weaknesses: ["Medical history", "Deep coverage ceiling was questioned"],
    nflComp: "Troy Polamalu (modernized)",
    grade: 8.6,
  },
  {
    slug: "minkah-fitzpatrick",
    firstName: "Minkah", lastName: "Fitzpatrick",
    position: "S", positionGroup: "SECONDARY",
    school: "Alabama", conference: "SEC", draftYear: 2018,
    heightInches: heightToInches(6, 0), weightLbs: 207,
    actualPick: 11, actualRound: 1, actualTeamAbbr: "MIA",
    summary: "Swiss Army defensive back with elite IQ and ball skills.",
    strengths: ["Instincts", "Versatility", "Ball skills"],
    weaknesses: ["Not a premium athletic tester", "Tackling technique varies"],
    nflComp: "Earl Thomas (coverage profile)",
    grade: 8.6,
  },
];
