import { heightToInches, type PlayerSeed } from "./types";

// 2026 class. Pre-draft big board as of April 2026. All scouting text is
// original summary material; measurements reflect publicly reported values
// where available. Best-effort numbers should be verified in admin before
// any production deployment.
export const PLAYERS_2026: PlayerSeed[] = [
  // -------------------- Tier 1 --------------------
  {
    slug: "caleb-downs",
    firstName: "Caleb", lastName: "Downs",
    position: "S", positionGroup: "SECONDARY",
    school: "Ohio State", conference: "Big Ten", draftYear: 2026,
    heightInches: heightToInches(6, 0), weightLbs: 205,
    age: 20.4, hometown: "Hoschton, GA",
    summary: "Generational safety prospect with rare processing, range, and tackling. Plays single-high, box, slot, and nickel blitzer at a high level.",
    strengths: ["Elite instincts and processing", "Sure tackler in space", "Positional flex", "Leadership intangibles"],
    weaknesses: ["Not a premium-sized safety", "Athletic testing is good but not elite", "Ball production modest for a top-tier safety"],
    nflComp: "Brian Branch with more range",
    grade: 9.3,
  },
  {
    slug: "anthony-hill-jr",
    firstName: "Anthony", lastName: "Hill Jr.",
    position: "LB", positionGroup: "LINEBACKER",
    school: "Texas", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 2), weightLbs: 235,
    age: 20.8, hometown: "DeSoto, TX",
    summary: "Alpha linebacker with elite pass-rush flex and plus coverage. Statistical outlier in TFLs and pressures for a true LB.",
    strengths: ["Elite closing burst", "Diagnosis and trigger", "Pass-rush production from LB", "Run-and-hit finishing"],
    weaknesses: ["Over-pursues at times", "Needs to clean up zone drops vs play-action", "Can play too hot"],
    nflComp: "Fred Warner with more juice",
    grade: 9.0,
  },
  {
    slug: "colin-simmons",
    firstName: "Colin", lastName: "Simmons",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Texas", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 3), weightLbs: 250,
    age: 20.6, hometown: "Duncanville, TX",
    summary: "Explosive bend-heavy rusher. SEC-leading freshman sack numbers backed up by a true pro rush plan as a sophomore.",
    strengths: ["Elite bend", "First-step explosion", "Productive vs top competition", "Counter package already forming"],
    weaknesses: ["Run anchor vs NFL OTs", "Frame has limited room to grow", "Average length for position"],
    nflComp: "Haason Reddick (more twitch)",
    grade: 8.8,
  },
  {
    slug: "peter-woods",
    firstName: "Peter", lastName: "Woods",
    position: "DT", positionGroup: "DEFENSIVE_LINE",
    school: "Clemson", conference: "ACC", draftYear: 2026,
    heightInches: heightToInches(6, 3), weightLbs: 305,
    age: 20.9, hometown: "Alabaster, AL",
    summary: "Three-down DT with scheme flex. Wins with twitch and power from multiple alignments. Elite youth profile.",
    strengths: ["Elite twitch for DT", "Multi-alignment versatility", "Power to collapse pocket", "Tackling technique"],
    weaknesses: ["Pass-rush counters thin", "Pad level can rise", "Production streaky"],
    nflComp: "Jeffery Simmons",
    grade: 8.7,
  },
  {
    slug: "tj-parker",
    firstName: "T.J.", lastName: "Parker",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Clemson", conference: "ACC", draftYear: 2026,
    heightInches: heightToInches(6, 3), weightLbs: 260,
    age: 20.9, hometown: "Phenix City, AL",
    summary: "Power edge with pro-caliber hand usage and a developing cross-chop. Held up as a true sophomore vs ACC OTs.",
    strengths: ["Hand usage and counters", "Run defense at the point", "Plus motor", "Converts speed to power"],
    weaknesses: ["Bend is average", "First step is good not elite", "Will need to add functional mass"],
    nflComp: "Derek Barnett (better finisher)",
    grade: 8.5,
  },
  {
    slug: "keldric-faulk",
    firstName: "Keldric", lastName: "Faulk",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Auburn", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 5), weightLbs: 288,
    age: 21.0, hometown: "Highland Home, AL",
    summary: "Rare-framed base end with interior rush flex. Projects as a prototype 4i or big 5-tech with sub-package interior snaps.",
    strengths: ["Elite length and frame", "Two-gap run defense", "Pass-rush upside inside", "Youth"],
    weaknesses: ["Bend limited by frame", "Conditioning over long drives", "Average get-off for elite EDGE grade"],
    nflComp: "DeForest Buckner (edge-heavy)",
    grade: 8.5,
  },

  // -------------------- Tier 2 --------------------
  {
    slug: "spencer-fano",
    firstName: "Spencer", lastName: "Fano",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Utah", conference: "Big 12", draftYear: 2026,
    heightInches: heightToInches(6, 5), weightLbs: 308,
    age: 20.7, hometown: "Provo, UT",
    summary: "Mauler OT with legitimate pass-pro feet. Dominant run-game finisher with scheme-agnostic NFL starter profile.",
    strengths: ["Run-game finisher", "Hand placement", "Anchor vs power", "Football IQ"],
    weaknesses: ["Arm length shorter than ideal", "Kick slide can get tall", "Needs reps vs elite bend"],
    nflComp: "Penei Sewell (lite)",
    grade: 8.5,
  },
  {
    slug: "francis-mauigoa",
    firstName: "Francis", lastName: "Mauigoa",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Miami", conference: "ACC", draftYear: 2026,
    heightInches: heightToInches(6, 6), weightLbs: 325,
    armInches: 34.25,
    age: 21.0, hometown: "Pago Pago, American Samoa",
    summary: "Three-year starter with prototype RT frame. Power through contact and plus recovery vs speed rushers.",
    strengths: ["Size and length", "Recovery athleticism", "Plus anchor", "Three-year starter resume"],
    weaknesses: ["Hand counters inconsistent", "Lateral quickness average", "Occasional high pad level"],
    nflComp: "Jawaan Taylor",
    grade: 8.2,
  },
  {
    slug: "kadyn-proctor",
    firstName: "Kadyn", lastName: "Proctor",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Alabama", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 7), weightLbs: 360,
    age: 20.7, hometown: "Iowa City, IA",
    summary: "Massive LT prospect with rare movement at size. Consistency is the only real flag on a top-of-class ceiling.",
    strengths: ["Rare size-movement combo", "Reach on perimeter blocks", "Anchor vs power", "Plus length"],
    weaknesses: ["Weight management narrative", "Hand timing varies", "Plays with inconsistent leverage"],
    nflComp: "Taylor Decker (bigger)",
    grade: 8.3,
  },
  {
    slug: "lt-overton",
    firstName: "LT", lastName: "Overton",
    position: "DT", positionGroup: "DEFENSIVE_LINE",
    school: "Alabama", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 5), weightLbs: 285,
    age: 22.0, hometown: "Milton, GA",
    summary: "Scheme-flex DL with premium length. Lines up from 3-tech to 5-tech and has developed into a disruptive power rusher.",
    strengths: ["Length and frame", "Multi-alignment versatility", "Power rush", "Run anchor"],
    weaknesses: ["Get-off is average", "Counter package thin", "Production tied to scheme"],
    nflComp: "Calais Campbell (lite)",
    grade: 8.0,
  },

  // -------------------- QBs --------------------
  {
    slug: "cade-klubnik",
    firstName: "Cade", lastName: "Klubnik",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Clemson", conference: "ACC", draftYear: 2026,
    heightInches: heightToInches(6, 2), weightLbs: 210,
    age: 22.0, hometown: "Austin, TX",
    summary: "Three-year starter with plus mobility and field-level leadership. Ball placement on intermediates is a strength.",
    strengths: ["Pocket poise", "Anticipation on intermediates", "Plus mobility", "Multi-year starter experience"],
    weaknesses: ["Average arm talent deep outside the numbers", "Will force into tight coverage", "Accuracy dips under duress"],
    nflComp: "Jared Goff (more mobile)",
    grade: 8.0,
  },
  {
    slug: "drew-allar",
    firstName: "Drew", lastName: "Allar",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Penn State", conference: "Big Ten", draftYear: 2026,
    heightInches: heightToInches(6, 5), weightLbs: 238,
    age: 21.4, hometown: "Medina, OH",
    summary: "Prototype size and arm with flashes of high-level play. Consistency on anticipation throws is the gating item.",
    strengths: ["Prototype size", "Arm strength at all levels", "Functional pocket mobility", "Clean ball placement on simple reads"],
    weaknesses: ["Anticipation on NFL windows", "Turnover-worthy plays when pressing", "Footwork on the move"],
    nflComp: "Carson Wentz",
    grade: 7.8,
  },
  {
    slug: "garrett-nussmeier",
    firstName: "Garrett", lastName: "Nussmeier",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "LSU", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 1), weightLbs: 200,
    age: 23.0, hometown: "Flower Mound, TX",
    summary: "Gunslinger with live arm and plus off-platform ability. Turnover worthy plays and frame are the questions.",
    strengths: ["Arm talent at all angles", "Aggressive downfield mentality", "Quick release", "Creation off-script"],
    weaknesses: ["Turnover-worthy plays", "Slight frame", "Inconsistent lower-body mechanics"],
    nflComp: "Baker Mayfield",
    grade: 7.6,
  },
  {
    slug: "lanorris-sellers",
    firstName: "LaNorris", lastName: "Sellers",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "South Carolina", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 3), weightLbs: 242,
    age: 21.3, hometown: "South Florence, SC",
    summary: "Rare size-speed QB with a live arm. Full-field processing and mechanics are still developing but the ceiling is elite.",
    strengths: ["Elite athletic profile", "Arm strength", "Plus pocket toughness", "Rushing production"],
    weaknesses: ["Short-area accuracy", "Full-field processing", "Decision-making vs two-high"],
    nflComp: "Josh Allen (college tape)",
    grade: 8.0,
  },
  // Dante Moore — intentionally omitted: has not declared for the draft.
  // Also in the DENYLIST in prisma/seed.ts to keep ESPN's prospect list from
  // re-adding him until he declares.
  {
    slug: "fernando-mendoza",
    firstName: "Fernando", lastName: "Mendoza",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Indiana", conference: "Big Ten", draftYear: 2026,
    heightInches: heightToInches(6, 5), weightLbs: 225,
    age: 22.6, hometown: "Miami, FL",
    summary: "Big-framed rhythm thrower who broke out at Indiana. Plus anticipation and ball placement headline the profile.",
    strengths: ["Size and frame", "Ball placement at all levels", "Pocket poise", "Decision-making"],
    weaknesses: ["Average athletic profile", "Deep-ball velocity", "Scheme-aided production"],
    nflComp: "Sam Howell (better accuracy)",
    grade: 7.5,
  },

  // -------------------- Skill position --------------------
  {
    slug: "jeremiyah-love",
    firstName: "Jeremiyah", lastName: "Love",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Notre Dame", conference: "Independent", draftYear: 2026,
    heightInches: heightToInches(6, 0), weightLbs: 206,
    fortyYard: 4.39,
    age: 20.9, hometown: "St. Louis, MO",
    summary: "Home-run hitter with rare one-cut explosion. Receiving chops and contact balance project a true three-down role.",
    strengths: ["Elite one-cut burst", "Home-run speed", "Receiving upside", "Contact balance for size"],
    weaknesses: ["Pass protection reps", "Durability concerns (knee)", "Will bounce outside too often"],
    nflComp: "Jahmyr Gibbs (bigger)",
    grade: 8.2,
  },
  {
    slug: "makai-lemon",
    firstName: "Makai", lastName: "Lemon",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "USC", conference: "Big Ten", draftYear: 2026,
    heightInches: heightToInches(5, 11), weightLbs: 190,
    age: 21.1, hometown: "Los Alamitos, CA",
    summary: "Separation king. Elite short-area quickness and route nuance from the slot make him a chain-mover at the next level.",
    strengths: ["Separation quickness", "Route nuance", "Reliable hands", "YAC creativity"],
    weaknesses: ["Frame and play strength", "Contested catch win rate", "Outside WR projection is a stretch"],
    nflComp: "Tyler Lockett",
    grade: 8.1,
  },
  {
    slug: "jordyn-tyson",
    firstName: "Jordyn", lastName: "Tyson",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Arizona State", conference: "Big 12", draftYear: 2026,
    heightInches: heightToInches(6, 1), weightLbs: 195,
    age: 21.6, hometown: "Allen, TX",
    summary: "Complete WR with plus route detail and tracking. Production at Arizona State cemented WR1 status in the class.",
    strengths: ["Route detail", "Ball tracking", "Separation", "Body control at catch point"],
    weaknesses: ["Medical history (collarbone)", "Average long speed", "Play strength vs press"],
    nflComp: "Chris Olave",
    grade: 8.2,
  },
  {
    slug: "carnell-tate",
    firstName: "Carnell", lastName: "Tate",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Ohio State", conference: "Big Ten", draftYear: 2026,
    heightInches: heightToInches(6, 2), weightLbs: 195,
    age: 21.1, hometown: "Bradenton, FL",
    summary: "Smooth outside WR with plus tracking. Production took off as a third-year starter in a loaded Ohio State room.",
    strengths: ["Deep-ball tracking", "Releases vs press", "Plus hands", "Size-speed blend"],
    weaknesses: ["Short-area quickness", "Average YAC profile", "Contested catch still developing"],
    nflComp: "Michael Pittman Jr.",
    grade: 7.9,
  },
  {
    slug: "cam-coleman",
    firstName: "Cam", lastName: "Coleman",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Auburn", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 3), weightLbs: 202,
    age: 20.6, hometown: "Phenix City, AL",
    summary: "Outside X with elite contested-catch and ball-tracking ability. Needs to clean up drops and press technique.",
    strengths: ["Contested catch", "Size-speed blend", "Red zone finisher", "Body control"],
    weaknesses: ["Drops", "Press technique", "Route nuance underdeveloped"],
    nflComp: "Terry McLaurin (early career)",
    grade: 7.8,
  },
  {
    slug: "nic-anderson",
    firstName: "Nic", lastName: "Anderson",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Oklahoma", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 4), weightLbs: 210,
    age: 21.3, hometown: "Katy, TX",
    summary: "Vertical X with rare catch radius. Durability is the story after a 2024 quad injury.",
    strengths: ["Catch radius", "Contested catch", "Size-speed blend", "Red zone utility"],
    weaknesses: ["Durability history", "Route nuance", "Press separation"],
    nflComp: "Jordan Addison (bigger frame)",
    grade: 7.6,
  },
  {
    slug: "bryant-wesco",
    firstName: "Bryant", lastName: "Wesco Jr.",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Clemson", conference: "ACC", draftYear: 2026,
    heightInches: heightToInches(6, 2), weightLbs: 190,
    age: 20.6, hometown: "Midlothian, TX",
    summary: "Long-striding field stretcher with sneaky release package. Frame growth will determine pro ceiling.",
    strengths: ["Deep speed", "Releases vs press", "Plus tracking", "Upside"],
    weaknesses: ["Slight frame", "Contested catch win rate", "YAC profile"],
    nflComp: "Calvin Austin III (taller)",
    grade: 7.6,
  },

  // -------------------- Defensive backs --------------------
  {
    slug: "jermod-mccoy",
    firstName: "Jermod", lastName: "McCoy",
    position: "CB", positionGroup: "SECONDARY",
    school: "Tennessee", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 0), weightLbs: 193,
    age: 21.5, hometown: "Canton, TX",
    summary: "Sticky outside corner with plus ball production. ACL recovery is the medical asterisk on an otherwise CB1 profile.",
    strengths: ["Ball skills", "Press feel", "Hips and recovery", "Willingness vs run"],
    weaknesses: ["Medical (ACL)", "Long speed is good not elite", "Tackling technique varies"],
    nflComp: "Byron Murphy Sr.",
    grade: 8.0,
  },
  {
    slug: "avieon-terrell",
    firstName: "Avieon", lastName: "Terrell",
    position: "CB", positionGroup: "SECONDARY",
    school: "Clemson", conference: "ACC", draftYear: 2026,
    heightInches: heightToInches(5, 11), weightLbs: 185,
    age: 21.2, hometown: "Atlanta, GA",
    summary: "Smaller-framed corner with elite movement. Brother of A.J.; similar tape with less length and more burst.",
    strengths: ["Elite hips and recovery", "Ball production", "Short-area quickness", "Pedigree"],
    weaknesses: ["Frame and play strength", "Jump-ball wins are rare", "Run-support willingness varies"],
    nflComp: "A.J. Terrell (lite)",
    grade: 7.9,
  },
  {
    slug: "mansoor-delane",
    firstName: "Mansoor", lastName: "Delane",
    position: "CB", positionGroup: "SECONDARY",
    school: "LSU", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 0), weightLbs: 190,
    age: 21.9, hometown: "Washington, DC",
    summary: "Ballhawk outside corner. Production at Virginia Tech carried into LSU and his profile is rising fast.",
    strengths: ["Ball production", "Zone awareness", "Plus hands at catch point", "Scheme flex"],
    weaknesses: ["Plays tall in press", "Recovery long speed", "Tackling consistency"],
    nflComp: "Darious Williams",
    grade: 7.8,
  },
  {
    slug: "kj-bolden",
    firstName: "KJ", lastName: "Bolden",
    position: "S", positionGroup: "SECONDARY",
    school: "Georgia", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 1), weightLbs: 200,
    age: 20.2, hometown: "Buford, GA",
    summary: "Rangy deep safety with elite athletic tools. Still learning the position but ceiling is top ten DB.",
    strengths: ["Range and closing speed", "Athletic profile", "Youth and ceiling", "Flexibility"],
    weaknesses: ["Eye discipline", "Tackling angles", "Communication still developing"],
    nflComp: "Kyle Hamilton (lite)",
    grade: 7.9,
  },
  {
    slug: "malachi-moore",
    firstName: "Malachi", lastName: "Moore",
    position: "S", positionGroup: "SECONDARY",
    school: "Alabama", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 0), weightLbs: 195,
    age: 23.1, hometown: "Trussville, AL",
    summary: "Veteran box safety / STAR defender. Sure tackler with plus communication skills. Age and athletic ceiling limit upside.",
    strengths: ["Experience and IQ", "Tackling", "Versatility at slot / box", "Plus communicator"],
    weaknesses: ["Older prospect", "Deep-coverage range limited", "Athletic testing will cap draft range"],
    nflComp: "Mike Edwards",
    grade: 7.4,
  },
  {
    slug: "keon-sabb",
    firstName: "Keon", lastName: "Sabb",
    position: "S", positionGroup: "SECONDARY",
    school: "Alabama", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 1), weightLbs: 210,
    age: 21.8, hometown: "Williamstown, NJ",
    summary: "Big, physical safety with plus athletic profile. Box / STAR fit with range to dabble in deep thirds.",
    strengths: ["Athletic profile", "Box physicality", "Positional versatility", "Blitzer from slot"],
    weaknesses: ["Tight hips in deep coverage", "Over-aggression on double moves", "Tackling angles"],
    nflComp: "Quandre Diggs",
    grade: 7.5,
  },

  // -------------------- Front seven --------------------
  {
    slug: "harold-perkins-jr",
    firstName: "Harold", lastName: "Perkins Jr.",
    position: "LB", positionGroup: "LINEBACKER",
    school: "LSU", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 1), weightLbs: 225,
    age: 21.5, hometown: "Cypress, TX",
    summary: "Hybrid LB/EDGE with elite closing burst. Came back from an ACL and the profile remains a premium chess piece.",
    strengths: ["Elite closing burst", "Pass-rush flex from LB", "Big-play production", "Athletic profile"],
    weaknesses: ["Medical (ACL)", "Size for full-time LB", "Take-on vs lead blocks"],
    nflComp: "Micah Parsons (slighter)",
    grade: 8.3,
  },
  {
    slug: "dylan-stewart",
    firstName: "Dylan", lastName: "Stewart",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "South Carolina", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 5), weightLbs: 250,
    age: 20.4, hometown: "Washington, DC",
    summary: "Explosive edge with rare get-off. Production ticked up in year two and the tools suggest a top-ten ceiling.",
    strengths: ["Elite first step", "Length and bend", "Youth", "Power on speed-to-power"],
    weaknesses: ["Run anchor", "Hand counters developing", "Production vs top OTs is small sample"],
    nflComp: "Danielle Hunter (early career)",
    grade: 8.5,
  },
  {
    slug: "rueben-bain-jr",
    firstName: "Rueben", lastName: "Bain Jr.",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Miami", conference: "ACC", draftYear: 2026,
    heightInches: heightToInches(6, 3), weightLbs: 275,
    age: 21.4, hometown: "Miami, FL",
    summary: "Power edge with scheme flex. Durability and inconsistent burst will determine draft range.",
    strengths: ["Power", "Run anchor at edge", "Multi-alignment flex", "Tape vs top ACC comp"],
    weaknesses: ["Durability history", "Average bend", "First step is ordinary"],
    nflComp: "Arik Armstead (lighter)",
    grade: 7.8,
  },
  {
    slug: "jaishawn-barham",
    firstName: "Jaishawn", lastName: "Barham",
    position: "LB", positionGroup: "LINEBACKER",
    school: "Michigan", conference: "Big Ten", draftYear: 2026,
    heightInches: heightToInches(6, 3), weightLbs: 245,
    age: 22.2, hometown: "Baltimore, MD",
    summary: "Big, rangy LB with blitz utility. Versatile piece that can play Mike or Sam at the next level.",
    strengths: ["Size and range", "Blitz upside", "Tackling radius", "Versatility"],
    weaknesses: ["Processing vs play-action", "Tight hips in man coverage", "Takes false steps"],
    nflComp: "Jaelan Phillips (LB version)",
    grade: 7.6,
  },
  {
    slug: "tyler-atkinson",
    firstName: "Tyler", lastName: "Atkinson",
    position: "LB", positionGroup: "LINEBACKER",
    school: "Georgia Tech", conference: "ACC", draftYear: 2026,
    heightInches: heightToInches(6, 2), weightLbs: 230,
    age: 20.7, hometown: "Grayson, GA",
    summary: "Rangy true LB with plus coverage ability. Breakout sophomore season pushed him into Day 1 conversation.",
    strengths: ["Coverage ability", "Range and speed", "Youth", "Playmaker mentality"],
    weaknesses: ["Take-on vs lead blocks", "Average size for position", "Overrun plays at times"],
    nflComp: "Jordyn Brooks",
    grade: 7.7,
  },
  {
    slug: "ethan-downs",
    firstName: "Ethan", lastName: "Downs",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Oklahoma", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 4), weightLbs: 270,
    age: 22.0, hometown: "Weatherford, OK",
    summary: "High-motor power edge. Every-down profile with scheme flex, though ceiling is capped by average bend.",
    strengths: ["Every-down profile", "Run defense", "Motor", "Hand strength"],
    weaknesses: ["Average bend", "First step is pedestrian", "Rush plan can improve"],
    nflComp: "Kingsley Jonathan",
    grade: 7.1,
  },

  // -------------------- Offensive line depth --------------------
  {
    slug: "olaus-alinen",
    firstName: "Olaus", lastName: "Alinen",
    position: "IOL", positionGroup: "OFFENSIVE_LINE",
    school: "Alabama", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 5), weightLbs: 323,
    age: 21.4, hometown: "Loomis Chaffee, CT",
    summary: "Finnish-born mauler with plus feet. Positional flex between LG and RT at the next level.",
    strengths: ["Run-game finisher", "Plus feet for size", "Anchor", "Positional versatility"],
    weaknesses: ["Hand placement can improve", "Pass-pro technique varies", "Limited SEC starts"],
    nflComp: "Nate Solder (guard-first)",
    grade: 7.5,
  },
  {
    slug: "cayden-green",
    firstName: "Cayden", lastName: "Green",
    position: "IOL", positionGroup: "OFFENSIVE_LINE",
    school: "Missouri", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(6, 4), weightLbs: 325,
    age: 20.8, hometown: "Lee's Summit, MO",
    summary: "Smooth interior mover with plus recovery. Two-year starter who projects as a plug-and-play guard.",
    strengths: ["Recovery athleticism", "Plus feet", "Hand placement", "Youth"],
    weaknesses: ["Pad level varies", "Anchor vs bull rushes", "Lateral quickness for reach blocks"],
    nflComp: "Wyatt Teller (lite)",
    grade: 7.6,
  },

  // -------------------- Other notable --------------------
  {
    slug: "nicholas-singleton",
    firstName: "Nicholas", lastName: "Singleton",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Penn State", conference: "Big Ten", draftYear: 2026,
    heightInches: heightToInches(5, 11), weightLbs: 227,
    fortyYard: 4.42,
    age: 21.5, hometown: "Reading, PA",
    summary: "Thick zone-scheme back with home-run speed. Returning production and pass-pro willingness raise the floor.",
    strengths: ["Long speed for size", "Wide-zone fit", "Plus pass pro", "Experience"],
    weaknesses: ["Average creativity", "Receiving role limited", "Shares touches at Penn State"],
    nflComp: "Najee Harris",
    grade: 7.5,
  },
  {
    slug: "kaytron-allen",
    firstName: "Kaytron", lastName: "Allen",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Penn State", conference: "Big Ten", draftYear: 2026,
    heightInches: heightToInches(5, 11), weightLbs: 219,
    age: 21.5, hometown: "Virginia Beach, VA",
    summary: "Patient contact-heavy back. Has the vision and short-area burst to hit NFL interior gaps.",
    strengths: ["Vision", "Contact balance", "Third-down value", "Durability"],
    weaknesses: ["Average long speed", "Not a home-run threat", "Production cut by shared workload"],
    nflComp: "David Montgomery",
    grade: 7.3,
  },
  {
    slug: "trevor-etienne",
    firstName: "Trevor", lastName: "Etienne",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Georgia", conference: "SEC", draftYear: 2026,
    heightInches: heightToInches(5, 9), weightLbs: 203,
    fortyYard: 4.48,
    age: 21.8, hometown: "Jennings, LA",
    summary: "Compact third-down back with plus receiving chops. Pedigree and scheme fit elevate the floor.",
    strengths: ["Receiving profile", "Pass-pro willingness", "Plus burst", "Scheme flex"],
    weaknesses: ["Size between the tackles", "Vision over the top", "Injury history"],
    nflComp: "James Cook",
    grade: 7.3,
  },
  {
    slug: "jake-briningstool",
    firstName: "Jake", lastName: "Briningstool",
    position: "TE", positionGroup: "OFFENSE_SKILL",
    school: "Clemson", conference: "ACC", draftYear: 2026,
    heightInches: heightToInches(6, 6), weightLbs: 241,
    age: 22.5, hometown: "Nashville, TN",
    summary: "Move TE with plus route feel. Separation quickness is the top trait; in-line blocking is the question.",
    strengths: ["Route feel", "Catch radius", "Hands", "Seam threat"],
    weaknesses: ["Inline blocking", "Play strength", "Average YAC"],
    nflComp: "Tucker Kraft (less physical)",
    grade: 7.4,
  },
  {
    slug: "jonah-coleman",
    firstName: "Jonah", lastName: "Coleman",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Washington", conference: "Big Ten", draftYear: 2026,
    heightInches: heightToInches(5, 9), weightLbs: 229,
    age: 22.0, hometown: "Stockton, CA",
    summary: "Thick contact-balance back with surprising receiving chops. Short but dense with plus tackle-breaking.",
    strengths: ["Contact balance", "Tackle-breaking", "Receiving ability", "Short-area burst"],
    weaknesses: ["Height limits vision", "Long-speed cap", "Pass-pro reps light"],
    nflComp: "Kareem Hunt (shorter)",
    grade: 7.3,
  },
];
