import { heightToInches, type PlayerSeed } from "./types";

// 2025 class. Measurements reflect publicly reported combine / pro day figures
// where available; a few are estimates and should be verified via admin before
// any production use. All scouting text is original summary material.
export const PLAYERS_2025: PlayerSeed[] = [
  {
    slug: "cam-ward",
    firstName: "Cam", lastName: "Ward",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Miami", conference: "ACC", draftYear: 2025,
    heightInches: heightToInches(6, 2), weightLbs: 219,
    armInches: 31.25, handInches: 9.75,
    age: 22.9, hometown: "West Columbia, TX",
    summary: "Fearless rhythm thrower with rare off-platform creativity and a live arm. Played at three schools and steadily climbed the QB ladder.",
    strengths: ["Plus arm talent at all three levels", "Late-play improvisation", "Calm vs pressure", "Aggressive downfield mentality"],
    weaknesses: ["Occasional hero-ball decisions", "Mechanics get loose under duress", "Asked to create too often in college"],
    nflComp: "Jordan Love",
    grade: 8.4,
  },
  {
    slug: "shedeur-sanders",
    firstName: "Shedeur", lastName: "Sanders",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Colorado", conference: "Big 12", draftYear: 2025,
    heightInches: heightToInches(6, 1), weightLbs: 212,
    handInches: 9.875,
    age: 23.1, hometown: "Canton, TX",
    summary: "Confident pocket operator with layered accuracy, anticipation, and one of the best clean-pocket ball placements in the class.",
    strengths: ["Ball placement to every level", "Tempo and timing", "Poise in muddy pockets", "Rhythm on intermediate crossers"],
    weaknesses: ["Average arm strength outside the numbers", "Holds on too long at times", "Sacked often at Colorado"],
    nflComp: "Kirk Cousins",
    grade: 7.9,
  },
  {
    slug: "travis-hunter",
    firstName: "Travis", lastName: "Hunter",
    position: "CB", positionGroup: "SECONDARY",
    school: "Colorado", conference: "Big 12", draftYear: 2025,
    heightInches: heightToInches(6, 0), weightLbs: 188,
    armInches: 30.75, handInches: 8.75, wingspanInches: 74.0,
    age: 21.5, hometown: "Suwanee, GA",
    summary: "Generational two-way talent. Elite ball skills at corner and WR with rare movement feel and body control on both sides of the ball.",
    strengths: ["Elite ball skills and tracking", "Fluid hips and mirror ability", "Competitive toughness", "Plays the ball like a WR"],
    weaknesses: ["Press technique still developing", "Needs to add play strength", "Usage split may slow pro acclimation"],
    nflComp: "Champ Bailey (cornerback profile)",
    grade: 9.2,
  },
  {
    slug: "abdul-carter",
    firstName: "Abdul", lastName: "Carter",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Penn State", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 3), weightLbs: 250,
    armInches: 32.0,
    age: 21.5, hometown: "Philadelphia, PA",
    summary: "Explosive pass rusher with a first-step that plays in every situation. Converted from off-ball LB and the arrow is still pointing up.",
    strengths: ["Elite get-off and bend", "Closing burst", "Hand quickness on stab-rip", "Plays with urgency every snap"],
    weaknesses: ["Anchor can improve vs run", "Limited rush-plan variety", "Still growing into edge role"],
    nflComp: "Micah Parsons",
    grade: 8.8,
  },
  {
    slug: "mason-graham",
    firstName: "Mason", lastName: "Graham",
    position: "DT", positionGroup: "DEFENSIVE_LINE",
    school: "Michigan", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 3), weightLbs: 296,
    armInches: 32.0,
    age: 21.8, hometown: "Anaheim, CA",
    summary: "Relentless three-tech with violent hands and advanced counters. Disruptive vs pass and sets a strong edge vs run.",
    strengths: ["Hand usage and counters", "Leverage off the snap", "Motor every play", "Knocks back OGs"],
    weaknesses: ["Length is merely average", "Not a premium athletic tester", "Fewer splash plays than expected"],
    nflComp: "Chris Jones (undersized)",
    grade: 8.6,
  },
  {
    slug: "will-campbell",
    firstName: "Will", lastName: "Campbell",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "LSU", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 6), weightLbs: 319,
    armInches: 32.625,
    age: 21.4, hometown: "Monroe, LA",
    summary: "Three-year starter at LT with elite intelligence, hand placement, and recovery athleticism. Arm length is the only real flag.",
    strengths: ["Processing and IQ", "Hand replacement in pass pro", "Anchor vs power", "Balanced kick slide"],
    weaknesses: ["Short arms for LT", "Occasional lunge vs long levers", "Hand timing can be early"],
    nflComp: "Joe Staley",
    grade: 8.5,
  },
  {
    slug: "ashton-jeanty",
    firstName: "Ashton", lastName: "Jeanty",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Boise State", conference: "Mountain West", draftYear: 2025,
    heightInches: heightToInches(5, 8), weightLbs: 211,
    age: 21.2, hometown: "Jacksonville, FL",
    summary: "Short-area wrecking ball with rare contact balance and tackle-breaking power. Produced a historic college season.",
    strengths: ["Contact balance is elite", "Jump cut and lateral agility", "Pass-pro willingness", "Finishing runs"],
    weaknesses: ["Not a home-run long speed profile", "Receiving game unproven at scale", "Heavy college workload"],
    nflComp: "Bijan Robinson meets Maurice Jones-Drew",
    grade: 8.7,
  },
  {
    slug: "tetairoa-mcmillan",
    firstName: "Tetairoa", lastName: "McMillan",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Arizona", conference: "Big 12", draftYear: 2025,
    heightInches: heightToInches(6, 4), weightLbs: 219,
    age: 22.1, hometown: "Servite, CA",
    summary: "Big-bodied X receiver with smooth route nuance for his frame and easily the best jump-ball player in the class.",
    strengths: ["Catch radius", "Body control on contested balls", "Route feel vs off coverage", "Red zone utility"],
    weaknesses: ["Long speed is merely functional", "Needs to win more vs press", "Occasional drops on routine throws"],
    nflComp: "Drake London",
    grade: 8.3,
  },
  {
    slug: "malaki-starks",
    firstName: "Malaki", lastName: "Starks",
    position: "S", positionGroup: "SECONDARY",
    school: "Georgia", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 1), weightLbs: 205,
    age: 21.1, hometown: "Jefferson, GA",
    summary: "Versatile chess piece who can play deep, box, or slot. Instincts and range stand out even on an elite Georgia defense.",
    strengths: ["Range and angles", "Positional versatility", "Football IQ and communication", "Tackling consistency"],
    weaknesses: ["Plays at a fast tempo and can overrun plays", "Ball production was down in 2024", "Does not test as twitchy as he plays"],
    nflComp: "Minkah Fitzpatrick",
    grade: 8.4,
  },
  {
    slug: "jalon-walker",
    firstName: "Jalon", lastName: "Walker",
    position: "LB", positionGroup: "LINEBACKER",
    school: "Georgia", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 1), weightLbs: 245,
    age: 21.4, hometown: "Salisbury, NC",
    summary: "Hybrid LB/EDGE with elite short-area explosion. Was Georgia's best pure pass rusher yet covers at a high level.",
    strengths: ["Explosive closing burst", "Pass-rush upside from multiple alignments", "Diagnose and trigger", "Effort on every snap"],
    weaknesses: ["Size for full-time LB", "Occasional overpursuit", "Tweener label is real"],
    nflComp: "Jamin Davis with pass-rush juice",
    grade: 8.2,
  },
  {
    slug: "armand-membou",
    firstName: "Armand", lastName: "Membou",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Missouri", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 4), weightLbs: 332,
    armInches: 33.375,
    age: 21.2, hometown: "Kansas City, MO",
    summary: "Rare blend of mass and movement. Short-area power in the run game with tournament-level feet in protection.",
    strengths: ["Elite grip strength", "Light feet for size", "Finishes blocks", "Athletic testing at top of class"],
    weaknesses: ["Hand placement inconsistent", "Pad level can rise", "Technically still developing"],
    nflComp: "Lael Collins",
    grade: 8.3,
  },
  {
    slug: "mykel-williams",
    firstName: "Mykel", lastName: "Williams",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Georgia", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 5), weightLbs: 265,
    armInches: 34.0,
    age: 20.5, hometown: "Columbus, GA",
    summary: "Prototype 4i/5-tech with length, power, and run-defense maturity. Pass-rush toolkit is promising but unpolished.",
    strengths: ["Length and power", "Two-gap ability vs run", "Anchor vs doubles", "Youth and frame"],
    weaknesses: ["Pass-rush plan is raw", "Ankle injury affected 2024 tape", "Bend is average"],
    nflComp: "Cam Jordan",
    grade: 8.0,
  },
  {
    slug: "jahdae-barron",
    firstName: "Jahdae", lastName: "Barron",
    position: "CB", positionGroup: "SECONDARY",
    school: "Texas", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(5, 11), weightLbs: 194,
    fortyYard: 4.39,
    age: 23.5, hometown: "Austin, TX",
    summary: "Scheme-flexible DB. Played slot, outside, and safety for Texas. Physical run supporter with tested ball skills.",
    strengths: ["Versatility across DB positions", "Tackling and toughness", "Ball production in 2024", "Play strength"],
    weaknesses: ["Average height and length", "Can get caught peeking", "Needs pro-level route recognition"],
    nflComp: "Jaire Alexander (slot-heavy)",
    grade: 8.1,
  },
  {
    slug: "tyler-warren",
    firstName: "Tyler", lastName: "Warren",
    position: "TE", positionGroup: "OFFENSE_SKILL",
    school: "Penn State", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 5), weightLbs: 257,
    age: 22.9, hometown: "Mechanicsville, VA",
    summary: "Swiss Army knife. Lined up inline, fullback, wildcat QB, and flex in college. YAC machine with rare ball skills for the position.",
    strengths: ["Run after catch", "Contested catch strength", "Versatility in formations", "Competitive toughness"],
    weaknesses: ["Straight-line speed is ordinary", "Inline blocking technique still developing", "Older prospect"],
    nflComp: "Travis Kelce (build similar, worse speed)",
    grade: 8.3,
  },
  {
    slug: "colston-loveland",
    firstName: "Colston", lastName: "Loveland",
    position: "TE", positionGroup: "OFFENSE_SKILL",
    school: "Michigan", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 5), weightLbs: 248,
    age: 21.3, hometown: "Gooding, ID",
    summary: "Modern move tight end with plus separation for the position and smooth ball skills from the slot or flex alignments.",
    strengths: ["Separation quickness", "Natural hands", "Route nuance for position", "Big frame to grow into"],
    weaknesses: ["In-line blocking needs work", "Play strength can improve", "Skinny lower half"],
    nflComp: "Evan Engram",
    grade: 8.1,
  },
  {
    slug: "matthew-golden",
    firstName: "Matthew", lastName: "Golden",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Texas", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(5, 11), weightLbs: 191,
    fortyYard: 4.29,
    age: 21.7, hometown: "Houston, TX",
    summary: "Elite vertical juice. Blazing 40 translates to game-speed separation on posts and nines.",
    strengths: ["True deep speed", "Smooth releases", "Comfortable in all alignments", "Special teams value"],
    weaknesses: ["Slight frame", "Contested catch volume is low", "Limited route tree sample"],
    nflComp: "DJ Moore (lean)",
    grade: 7.9,
  },
  {
    slug: "luther-burden",
    firstName: "Luther", lastName: "Burden III",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Missouri", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 0), weightLbs: 206,
    age: 21.7, hometown: "St. Louis, MO",
    summary: "Compact YAC monster. Short-area quickness and physicality make him a nightmare on manufactured touches.",
    strengths: ["Elite YAC profile", "Contact balance", "Versatile slot usage", "Plays bigger than size"],
    weaknesses: ["Route tree projection outside", "Production dipped in 2024", "Hands are inconsistent"],
    nflComp: "Deebo Samuel",
    grade: 7.9,
  },
  {
    slug: "emeka-egbuka",
    firstName: "Emeka", lastName: "Egbuka",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Ohio State", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 1), weightLbs: 205,
    age: 22.6, hometown: "Steilacoom, WA",
    summary: "Polished all-three-levels route runner. Best traits are route detail and reliability, not top-end testing.",
    strengths: ["Route-running technician", "Reliable hands", "Blocking effort", "Plug-and-play floor"],
    weaknesses: ["Not a burner", "Average play strength", "Limited vertical highlight reel"],
    nflComp: "Chris Olave (floor)",
    grade: 8.0,
  },
  {
    slug: "kelvin-banks",
    firstName: "Kelvin", lastName: "Banks Jr.",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Texas", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 5), weightLbs: 315,
    armInches: 33.25,
    age: 21.0, hometown: "Humble, TX",
    summary: "Three-year LT starter with smooth feet, balance, and power. Arrow up with upside to stay at LT in the NFL.",
    strengths: ["Balanced kick slide", "Recovery athleticism", "Plus anchor", "Three-year starter resume"],
    weaknesses: ["Arm length borderline", "Hand placement can improve", "Has been beat by long-armed rushers"],
    nflComp: "Tristan Wirfs (lite)",
    grade: 8.1,
  },
  {
    slug: "josh-simmons",
    firstName: "Josh", lastName: "Simmons",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Ohio State", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 5), weightLbs: 310,
    age: 22.0, hometown: "San Diego, CA",
    summary: "High ceiling LT with elite quickness in protection before a season-ending knee injury. Medical is the whole story.",
    strengths: ["Elite mirror and recovery", "Quickness off the ball", "Pass-pro tempo", "Smooth bend"],
    weaknesses: ["Medical (knee)", "Play strength in run game", "Limited clean tape in 2024"],
    nflComp: "Rashawn Slater",
    grade: 8.0,
  },
  {
    slug: "will-johnson",
    firstName: "Will", lastName: "Johnson",
    position: "CB", positionGroup: "SECONDARY",
    school: "Michigan", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 2), weightLbs: 194,
    age: 21.2, hometown: "Grosse Pointe, MI",
    summary: "Long, smooth press corner with ball skills. Medicals and a modest athletic profile pushed him off the top of the class.",
    strengths: ["Size and length", "Ball skills", "Press technique", "High football IQ"],
    weaknesses: ["Long speed concerns", "Medical history", "Change of direction is average"],
    nflComp: "Pat Surtain II (less twitch)",
    grade: 8.0,
  },
  {
    slug: "nic-scourton",
    firstName: "Nic", lastName: "Scourton",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Texas A&M", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 3), weightLbs: 257,
    age: 20.7, hometown: "Bryan, TX",
    summary: "Powerful edge setter with a developing rush repertoire. Heavy hands and run-defense maturity headline the profile.",
    strengths: ["Run defense at the point", "Hand strength", "Cross-chop counter", "Youth"],
    weaknesses: ["Average bend", "Burst off the snap is ordinary", "Rush plan needs variety"],
    nflComp: "Preston Smith",
    grade: 7.8,
  },
  {
    slug: "walter-nolen",
    firstName: "Walter", lastName: "Nolen",
    position: "DT", positionGroup: "DEFENSIVE_LINE",
    school: "Ole Miss", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 3), weightLbs: 296,
    age: 21.1, hometown: "Powder Springs, GA",
    summary: "Disruptive interior penetrator with elite first step. Consistency and pad level are the gating items.",
    strengths: ["Explosive first step", "Twitch rare for interior", "Pass-rush upside", "Violent hands"],
    weaknesses: ["Inconsistent effort snap to snap", "Pad level rises", "Two-gap discipline vs run"],
    nflComp: "Jeffery Simmons",
    grade: 8.0,
  },
  {
    slug: "derrick-harmon",
    firstName: "Derrick", lastName: "Harmon",
    position: "DT", positionGroup: "DEFENSIVE_LINE",
    school: "Oregon", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 4), weightLbs: 313,
    age: 22.2, hometown: "Detroit, MI",
    summary: "Big, twitched-up interior defender. Pass-rush production took off in 2024 with Oregon's aggressive scheme.",
    strengths: ["Length and size", "Pass-rush twitch for size", "Hand strength", "Run anchor"],
    weaknesses: ["Pad level consistency", "Pro counters are thin", "Conditioning in long drives"],
    nflComp: "Sebastian Joseph-Day",
    grade: 7.8,
  },
  {
    slug: "kenneth-grant",
    firstName: "Kenneth", lastName: "Grant",
    position: "DT", positionGroup: "DEFENSIVE_LINE",
    school: "Michigan", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 3), weightLbs: 330,
    age: 21.3, hometown: "Merrillville, IN",
    summary: "Massive nose with surprising movement. Fits as a base 1-tech with positional flex to 3-tech in sub packages.",
    strengths: ["Size and anchor", "Rare movement for frame", "Hand strength", "Played in a winning culture"],
    weaknesses: ["Pass-rush counters thin", "Snap count awareness", "Won by size more than technique"],
    nflComp: "Dexter Lawrence (lite)",
    grade: 7.8,
  },
  {
    slug: "tyler-booker",
    firstName: "Tyler", lastName: "Booker",
    position: "IOL", positionGroup: "OFFENSIVE_LINE",
    school: "Alabama", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 5), weightLbs: 321,
    armInches: 34.0,
    age: 21.1, hometown: "New Haven, CT",
    summary: "Plug-and-play interior mauler. Power, length, and room-fit temperament headline his day-one starter profile.",
    strengths: ["Elite grip and power", "Leadership and intangibles", "Length for the position", "Run-game mover"],
    weaknesses: ["Lateral quickness average", "Struggles in space vs quicker DTs", "Some reach issues"],
    nflComp: "Zack Martin (build)",
    grade: 7.9,
  },
  {
    slug: "jaxson-dart",
    firstName: "Jaxson", lastName: "Dart",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Ole Miss", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 2), weightLbs: 223,
    age: 21.8, hometown: "Kaysville, UT",
    summary: "Rhythm starter with sneaky mobility. Lane Kiffin schemes up easy throws but Dart flashes anticipation and pocket movement.",
    strengths: ["Pocket movement", "Anticipation on in-breakers", "Rushing ability", "Leadership"],
    weaknesses: ["Reads can freeze on layered concepts", "Mid-level arm talent", "Scheme-dependent production"],
    nflComp: "Baker Mayfield",
    grade: 7.5,
  },
  {
    slug: "shavon-revel",
    firstName: "Shavon", lastName: "Revel Jr.",
    position: "CB", positionGroup: "SECONDARY",
    school: "East Carolina", conference: "AAC", draftYear: 2025,
    heightInches: heightToInches(6, 2), weightLbs: 194,
    age: 24.0, hometown: "Fayetteville, NC",
    summary: "Lengthy outside corner with toughness and ball skills. 2024 ACL injury is the medical asterisk.",
    strengths: ["Length and height", "Press ability", "Ball skills", "Run support toughness"],
    weaknesses: ["Coming off ACL", "Older prospect", "Smaller school level of competition"],
    nflComp: "Michael Davis",
    grade: 7.6,
  },
  {
    slug: "omarion-hampton",
    firstName: "Omarion", lastName: "Hampton",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "North Carolina", conference: "ACC", draftYear: 2025,
    heightInches: heightToInches(6, 0), weightLbs: 221,
    fortyYard: 4.46,
    age: 21.7, hometown: "Clayton, NC",
    summary: "Three-down back with size and home-run speed. Production and testing both align to an early RB1 outcome.",
    strengths: ["Size-speed blend", "Finishing power", "Receiving-game upside", "Workhorse profile"],
    weaknesses: ["Vision over the top could improve", "Pass-pro reads", "Will run high"],
    nflComp: "Saquon Barkley (lite)",
    grade: 8.0,
  },
  {
    slug: "treveyon-henderson",
    firstName: "TreVeyon", lastName: "Henderson",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Ohio State", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(5, 10), weightLbs: 202,
    fortyYard: 4.43,
    age: 22.6, hometown: "Hopewell, VA",
    summary: "Third-down ace with receiving chops and pass-pro willingness. Explosive in space with injury history as a flag.",
    strengths: ["Third-down value", "Pass protection at elite level for RB", "Home-run burst", "Receiving ability"],
    weaknesses: ["Durability history", "Not a heavy between-the-tackles profile", "Weight is borderline"],
    nflComp: "James White with more juice",
    grade: 7.8,
  },
  {
    slug: "quinshon-judkins",
    firstName: "Quinshon", lastName: "Judkins",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Ohio State", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(5, 11), weightLbs: 221,
    fortyYard: 4.48,
    age: 21.5, hometown: "Pike Road, AL",
    summary: "Thick, physical runner with plus testing. Contact balance and short-yardage role translates immediately.",
    strengths: ["Short-yardage conversion", "Contact balance", "Surprising testing for build", "Tackle-breaking"],
    weaknesses: ["Average vision", "Receiving game is a projection", "Rarely makes men miss in space"],
    nflComp: "David Montgomery",
    grade: 7.6,
  },
  {
    slug: "kaleb-johnson",
    firstName: "Kaleb", lastName: "Johnson",
    position: "RB", positionGroup: "OFFENSE_SKILL",
    school: "Iowa", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 1), weightLbs: 224,
    age: 21.9, hometown: "Hamilton, OH",
    summary: "One-cut zone back with long speed for a big body. Fit-dependent but has an elite scheme ceiling.",
    strengths: ["Long speed at size", "Wide zone fit", "Decisive one-cut", "Durable workhorse"],
    weaknesses: ["Limited creativity", "Average in gap schemes", "Third-down role unproven"],
    nflComp: "Javonte Williams",
    grade: 7.5,
  },
  {
    slug: "jalen-milroe",
    firstName: "Jalen", lastName: "Milroe",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "Alabama", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 2), weightLbs: 217,
    age: 22.5, hometown: "Katy, TX",
    summary: "Elite athlete with a true arm. Processing and short-to-intermediate accuracy need NFL-level coaching investment.",
    strengths: ["Elite rushing upside at QB", "Arm strength", "Toughness", "Deep-ball power"],
    weaknesses: ["Full-field reads", "Short and intermediate accuracy", "Ball security under pressure"],
    nflComp: "Anthony Richardson",
    grade: 7.3,
  },
  {
    slug: "tyleik-williams",
    firstName: "Tyleik", lastName: "Williams",
    position: "DT", positionGroup: "DEFENSIVE_LINE",
    school: "Ohio State", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 3), weightLbs: 327,
    age: 22.6, hometown: "Manassas, VA",
    summary: "Massive interior rusher with surprising get-off for his size. Fits best as a 1-tech with pass-rush snaps.",
    strengths: ["Power and size", "Get-off for size", "Run anchor", "Plus length"],
    weaknesses: ["Conditioning", "Pass-rush plan", "Inconsistent leverage"],
    nflComp: "Javon Hargrave (bigger)",
    grade: 7.7,
  },
  {
    slug: "donovan-jackson",
    firstName: "Donovan", lastName: "Jackson",
    position: "IOL", positionGroup: "OFFENSIVE_LINE",
    school: "Ohio State", conference: "Big Ten", draftYear: 2025,
    heightInches: heightToInches(6, 4), weightLbs: 315,
    age: 22.4, hometown: "Bellaire, TX",
    summary: "Plug-and-play guard with positional flex to tackle in a pinch. Four-year starter resume and plus football IQ.",
    strengths: ["Experience and IQ", "Hand placement", "Anchor vs power", "Plus leadership"],
    weaknesses: ["Average lateral quickness", "Struggles with quick twitch DTs", "Reach blocks are tougher"],
    nflComp: "Wyatt Teller",
    grade: 7.6,
  },
  {
    slug: "mike-green",
    firstName: "Mike", lastName: "Green",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Marshall", conference: "Sun Belt", draftYear: 2025,
    heightInches: heightToInches(6, 3), weightLbs: 248,
    age: 22.6, hometown: "Williamsburg, VA",
    summary: "Relentless edge rusher who led FBS in sacks. Bend, speed-to-power, and motor stand out even against lower competition.",
    strengths: ["Bend around the arc", "Speed-to-power conversion", "Motor", "Versatile rush plan"],
    weaknesses: ["Level of competition", "Run anchor vs NFL OTs", "Average mass for every-down role"],
    nflComp: "Haason Reddick",
    grade: 7.7,
  },
  {
    slug: "shemar-stewart",
    firstName: "Shemar", lastName: "Stewart",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Texas A&M", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 5), weightLbs: 267,
    fortyYard: 4.59,
    age: 21.5, hometown: "Opa-locka, FL",
    summary: "Traits explosion with limited production. Elite athletic testing and a ceiling that will justify a high investment for some teams.",
    strengths: ["Elite athletic profile", "Length", "Power", "Youth"],
    weaknesses: ["Limited sack production", "Inconsistent rush plan", "Raw overall"],
    nflComp: "Ziggy Ansah",
    grade: 7.6,
  },
  {
    slug: "jihaad-campbell",
    firstName: "Jihaad", lastName: "Campbell",
    position: "LB", positionGroup: "LINEBACKER",
    school: "Alabama", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(6, 3), weightLbs: 235,
    age: 21.5, hometown: "Erial, NJ",
    summary: "Rangy LB with plus athletic profile and pass-rush flex. Alabama used him as a move piece that can blitz.",
    strengths: ["Range and speed", "Pass-rush upside", "Size for LB", "Playmaker"],
    weaknesses: ["Can overrun plays", "Take-on vs lead blocks", "Needs processing reps"],
    nflComp: "Devin White",
    grade: 7.8,
  },
  {
    slug: "grey-zabel",
    firstName: "Grey", lastName: "Zabel",
    position: "IOL", positionGroup: "OFFENSIVE_LINE",
    school: "North Dakota State", conference: "MVFC", draftYear: 2025,
    heightInches: heightToInches(6, 6), weightLbs: 312,
    age: 23.4, hometown: "Pierre, SD",
    summary: "Positional flex piece who graded out elite at the Senior Bowl. Can play center, guard, or tackle in a pinch.",
    strengths: ["Positional versatility", "Senior Bowl riser", "Technique and IQ", "Motor"],
    weaknesses: ["FCS level of competition", "Arm length average", "Not a dominant athlete"],
    nflComp: "Will Hernandez (OG version)",
    grade: 7.4,
  },
  {
    slug: "maxwell-hairston",
    firstName: "Maxwell", lastName: "Hairston",
    position: "CB", positionGroup: "SECONDARY",
    school: "Kentucky", conference: "SEC", draftYear: 2025,
    heightInches: heightToInches(5, 11), weightLbs: 183,
    fortyYard: 4.28,
    age: 22.5, hometown: "West Bloomfield, MI",
    summary: "Burner corner with elite closing speed. Slight frame and tackling need to catch up to his movement skills.",
    strengths: ["Elite long speed", "Ball production", "Hips and recovery", "Scheme-flex coverage"],
    weaknesses: ["Frame and play strength", "Tackling", "Will struggle in press vs big WRs"],
    nflComp: "Donte Jackson",
    grade: 7.6,
  },
  {
    slug: "azareye-thomas",
    firstName: "Azareye", lastName: "Thomas",
    position: "CB", positionGroup: "SECONDARY",
    school: "Florida State", conference: "ACC", draftYear: 2025,
    heightInches: heightToInches(6, 2), weightLbs: 195,
    age: 21.2, hometown: "Crowley, LA",
    summary: "Long-framed zone corner who thrives in press-match. Long speed is the question on a very appealing traits prospect.",
    strengths: ["Length and frame", "Press technique", "Willingness vs run", "Zone awareness"],
    weaknesses: ["Long speed", "High hips in deep coverage", "Did not test well"],
    nflComp: "Tariq Woolen (slower)",
    grade: 7.3,
  },
];
