import { heightToInches, type PlayerSeed } from "./types";

export const PLAYERS_2024: PlayerSeed[] = [
  {
    slug: "caleb-williams",
    firstName: "Caleb", lastName: "Williams",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "USC", conference: "Pac-12", draftYear: 2024,
    heightInches: heightToInches(6, 1), weightLbs: 214,
    handInches: 9.875,
    actualPick: 1, actualRound: 1, actualTeamAbbr: "CHI",
    age: 22.6, hometown: "Washington, D.C.",
    summary: "Franchise-level creator with a live arm and rare improvisation feel. Boom-or-bust player on structure.",
    strengths: ["Off-platform arm talent", "Creation outside structure", "Downfield accuracy", "Playmaking"],
    weaknesses: ["Sacks under pressure", "Can abandon clean pockets", "Lower body mechanics vary"],
    nflComp: "Patrick Mahomes (lower floor)",
    grade: 8.8,
  },
  {
    slug: "jayden-daniels",
    firstName: "Jayden", lastName: "Daniels",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "LSU", conference: "SEC", draftYear: 2024,
    heightInches: heightToInches(6, 4), weightLbs: 210,
    actualPick: 2, actualRound: 1, actualTeamAbbr: "WAS",
    age: 23.6, hometown: "San Bernardino, CA",
    summary: "Dual-threat with elite deep-ball touch. Heisman season showcased anticipation and big-play arm.",
    strengths: ["Deep-ball accuracy", "Rushing ability", "Poise under pressure", "Production at premium level"],
    weaknesses: ["Slight frame concerns", "Durability questions", "Short-area accuracy variance"],
    nflComp: "Lamar Jackson (taller)",
    grade: 8.6,
  },
  {
    slug: "drake-maye",
    firstName: "Drake", lastName: "Maye",
    position: "QB", positionGroup: "OFFENSE_SKILL",
    school: "North Carolina", conference: "ACC", draftYear: 2024,
    heightInches: heightToInches(6, 4), weightLbs: 223,
    actualPick: 3, actualRound: 1, actualTeamAbbr: "NE",
    age: 21.7, hometown: "Huntersville, NC",
    summary: "Tall, strong-armed passer with creation ability. Needs to clean up decision-making but the tools are high end.",
    strengths: ["Arm strength at all levels", "Size and build", "Creation ability", "Anticipation on intermediates"],
    weaknesses: ["Turnover-worthy plays", "Footwork mechanics", "Accuracy on high-difficulty throws"],
    nflComp: "Justin Herbert",
    grade: 8.5,
  },
  {
    slug: "marvin-harrison-jr",
    firstName: "Marvin", lastName: "Harrison Jr.",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Ohio State", conference: "Big Ten", draftYear: 2024,
    heightInches: heightToInches(6, 3), weightLbs: 209,
    actualPick: 4, actualRound: 1, actualTeamAbbr: "ARI",
    age: 22.1, hometown: "Philadelphia, PA",
    summary: "Prototype X with elite route running, body control, and catch point strength. Ready-made WR1.",
    strengths: ["Route running", "Catch point", "Plus-plus bloodlines", "All-three-levels production"],
    weaknesses: ["Did not test at combine", "Average play strength vs press", "Modest blocking effort"],
    nflComp: "His father",
    grade: 8.9,
  },
  {
    slug: "joe-alt",
    firstName: "Joe", lastName: "Alt",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Notre Dame", conference: "Independent", draftYear: 2024,
    heightInches: heightToInches(6, 9), weightLbs: 321,
    actualPick: 5, actualRound: 1, actualTeamAbbr: "LAC",
    age: 21.8, hometown: "North Oaks, MN",
    summary: "Rare size-movement blend. Clean LT technique with positional value at a premium.",
    strengths: ["Elite size-movement combo", "Hand placement", "Anchor vs power", "Ready-made LT"],
    weaknesses: ["Average arm length for his height", "Hand counters can improve", "Limited pro-style reps vs speed-to-power"],
    nflComp: "Ryan Clady",
    grade: 8.8,
  },
  {
    slug: "malik-nabers",
    firstName: "Malik", lastName: "Nabers",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "LSU", conference: "SEC", draftYear: 2024,
    heightInches: heightToInches(6, 0), weightLbs: 199,
    actualPick: 6, actualRound: 1, actualTeamAbbr: "NYG",
    age: 20.9, hometown: "Lafayette, LA",
    summary: "Explosive all-around WR with elite burst and YAC ability. Do-everything WR1 upside.",
    strengths: ["Burst out of breaks", "YAC ability", "All alignments", "Production at elite level"],
    weaknesses: ["Concentration drops", "Frame is lean", "Contested catch sample small"],
    nflComp: "Stefon Diggs",
    grade: 8.7,
  },
  {
    slug: "brock-bowers",
    firstName: "Brock", lastName: "Bowers",
    position: "TE", positionGroup: "OFFENSE_SKILL",
    school: "Georgia", conference: "SEC", draftYear: 2024,
    heightInches: heightToInches(6, 3), weightLbs: 243,
    actualPick: 13, actualRound: 1, actualTeamAbbr: "LV",
    age: 21.7, hometown: "Napa, CA",
    summary: "Rare move TE with elite separation, YAC and route nuance. Smaller frame but production has been immense.",
    strengths: ["Separation quickness", "Elite YAC", "Route nuance", "Versatile alignment"],
    weaknesses: ["Below-average inline blocker", "Frame is lean", "Average catch radius for size"],
    nflComp: "Travis Kelce (lite)",
    grade: 8.6,
  },
  {
    slug: "rome-odunze",
    firstName: "Rome", lastName: "Odunze",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Washington", conference: "Pac-12", draftYear: 2024,
    heightInches: heightToInches(6, 3), weightLbs: 212,
    actualPick: 9, actualRound: 1, actualTeamAbbr: "CHI",
    age: 22.3, hometown: "Las Vegas, NV",
    summary: "Prototype size-speed X receiver with elite contested catch and strong route detail.",
    strengths: ["Contested catch", "Size-speed blend", "Route details", "Plus-plus hands"],
    weaknesses: ["Not an elite separator vs tight coverage", "YAC profile is average", "Release package vs press can grow"],
    nflComp: "Mike Evans",
    grade: 8.4,
  },
  {
    slug: "jc-latham",
    firstName: "JC", lastName: "Latham",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Alabama", conference: "SEC", draftYear: 2024,
    heightInches: heightToInches(6, 6), weightLbs: 342,
    actualPick: 7, actualRound: 1, actualTeamAbbr: "TEN",
    age: 21.3, hometown: "Oak Creek, WI",
    summary: "Massive mauler with strong pass-pro base. RT profile with scheme-agile run-game fit.",
    strengths: ["Size and power", "Anchor vs power", "Run-game finisher", "Pass-pro strength"],
    weaknesses: ["Heavy feet in space", "Struggles vs elite speed off the edge", "Limited LT upside"],
    nflComp: "Tristan Wirfs (RT side)",
    grade: 8.2,
  },
  {
    slug: "terrion-arnold",
    firstName: "Terrion", lastName: "Arnold",
    position: "CB", positionGroup: "SECONDARY",
    school: "Alabama", conference: "SEC", draftYear: 2024,
    heightInches: heightToInches(6, 0), weightLbs: 189,
    actualPick: 24, actualRound: 1, actualTeamAbbr: "DET",
    age: 21.5, hometown: "Tallahassee, FL",
    summary: "Scheme-flex corner with physical coverage demeanor and ball skills in off-man.",
    strengths: ["Ball skills", "Zone instincts", "Willingness vs run", "Short-area quickness"],
    weaknesses: ["Gets handsy downfield", "Over-aggression on double moves", "Needs press polish"],
    nflComp: "Jaire Alexander",
    grade: 8.1,
  },
  {
    slug: "quinyon-mitchell",
    firstName: "Quinyon", lastName: "Mitchell",
    position: "CB", positionGroup: "SECONDARY",
    school: "Toledo", conference: "MAC", draftYear: 2024,
    heightInches: heightToInches(5, 11), weightLbs: 195,
    fortyYard: 4.33,
    actualPick: 22, actualRound: 1, actualTeamAbbr: "PHI",
    age: 22.3, hometown: "Williston, FL",
    summary: "Athletic, physical corner with elite testing. Small-school level of competition was the only real knock.",
    strengths: ["Elite testing profile", "Press feel", "Ball production", "Run support"],
    weaknesses: ["Level of competition", "Length is average", "Some recovery plays masked by speed"],
    nflComp: "James Bradberry",
    grade: 8.2,
  },
  {
    slug: "dallas-turner",
    firstName: "Dallas", lastName: "Turner",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Alabama", conference: "SEC", draftYear: 2024,
    heightInches: heightToInches(6, 3), weightLbs: 247,
    actualPick: 17, actualRound: 1, actualTeamAbbr: "MIN",
    age: 21.4, hometown: "Fort Lauderdale, FL",
    summary: "Speed-to-power edge with elite first step. Rush plan and run defense still developing.",
    strengths: ["First step", "Closing burst", "Bend", "Pass-rush upside"],
    weaknesses: ["Run defense", "Inconsistent hand use", "Anchor vs OTs"],
    nflComp: "Kayvon Thibodeaux",
    grade: 8.0,
  },
  {
    slug: "laiatu-latu",
    firstName: "Laiatu", lastName: "Latu",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "UCLA", conference: "Pac-12", draftYear: 2024,
    heightInches: heightToInches(6, 5), weightLbs: 259,
    actualPick: 15, actualRound: 1, actualTeamAbbr: "IND",
    age: 23.8, hometown: "Sacramento, CA",
    summary: "Refined pass rusher with diverse hand counters and advanced plan. Medical history is a real factor.",
    strengths: ["Elite rush plan", "Hand counters", "Production vs top comp", "Motor"],
    weaknesses: ["Medical flags (neck)", "Older prospect", "Athletic ceiling is average"],
    nflComp: "Chris Jones (edge version)",
    grade: 8.2,
  },
  {
    slug: "jared-verse",
    firstName: "Jared", lastName: "Verse",
    position: "EDGE", positionGroup: "DEFENSIVE_LINE",
    school: "Florida State", conference: "ACC", draftYear: 2024,
    heightInches: heightToInches(6, 4), weightLbs: 254,
    actualPick: 19, actualRound: 1, actualTeamAbbr: "LAR",
    age: 23.7, hometown: "Paulsboro, NJ",
    summary: "Powerful, well-rounded edge. Plays with plus effort and has the frame to hold up as an every-down 4-3 DE.",
    strengths: ["Power", "Every-down profile", "Run defense", "Motor"],
    weaknesses: ["Average bend", "Older prospect", "Pass-rush ceiling is solid but not elite"],
    nflComp: "Carl Lawson",
    grade: 7.9,
  },
  {
    slug: "byron-murphy-ii",
    firstName: "Byron", lastName: "Murphy II",
    position: "DT", positionGroup: "DEFENSIVE_LINE",
    school: "Texas", conference: "Big 12", draftYear: 2024,
    heightInches: heightToInches(6, 1), weightLbs: 308,
    actualPick: 16, actualRound: 1, actualTeamAbbr: "SEA",
    age: 21.7, hometown: "DeSoto, TX",
    summary: "Undersized pass-rushing 3-tech with elite explosion. Short but stout and plays with leverage.",
    strengths: ["First step", "Leverage", "Hand use", "Pass rush inside"],
    weaknesses: ["Height and length", "Two-gap ability"],
    nflComp: "Aaron Donald (less freakish)",
    grade: 8.0,
  },
  {
    slug: "cooper-dejean",
    firstName: "Cooper", lastName: "DeJean",
    position: "CB", positionGroup: "SECONDARY",
    school: "Iowa", conference: "Big Ten", draftYear: 2024,
    heightInches: heightToInches(6, 1), weightLbs: 203,
    actualPick: 40, actualRound: 2, actualTeamAbbr: "PHI",
    age: 21.5, hometown: "OdeBolt, IA",
    summary: "Swiss Army knife DB with instincts, ball skills, and positional flex. Slot/safety hybrid upside.",
    strengths: ["Positional flex", "Ball skills", "Instincts", "Tackling"],
    weaknesses: ["Recovery speed vs top-end burners", "Tight hips in open-field coverage"],
    nflComp: "Minkah Fitzpatrick",
    grade: 8.0,
  },
  {
    slug: "brian-thomas-jr",
    firstName: "Brian", lastName: "Thomas Jr.",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "LSU", conference: "SEC", draftYear: 2024,
    heightInches: heightToInches(6, 3), weightLbs: 209,
    fortyYard: 4.33,
    actualPick: 23, actualRound: 1, actualTeamAbbr: "JAX",
    age: 21.7, hometown: "Walker, LA",
    summary: "Size-speed vertical threat with big-play profile. Ball skills and contested catch strength raise the floor.",
    strengths: ["Size-speed blend", "Contested catch", "Deep-ball tracking"],
    weaknesses: ["Route nuance underdeveloped", "Average quickness in short areas"],
    nflComp: "Mike Williams",
    grade: 8.1,
  },
  {
    slug: "xavier-worthy",
    firstName: "Xavier", lastName: "Worthy",
    position: "WR", positionGroup: "OFFENSE_SKILL",
    school: "Texas", conference: "Big 12", draftYear: 2024,
    heightInches: heightToInches(5, 11), weightLbs: 165,
    fortyYard: 4.21,
    actualPick: 28, actualRound: 1, actualTeamAbbr: "KC",
    age: 21.2, hometown: "Fresno, CA",
    summary: "Record-setting combine speed. Vertical threat and manufactured-touch weapon.",
    strengths: ["World-class speed", "Manufactured-touch ability", "Special teams value"],
    weaknesses: ["Frame and play strength", "Press coverage", "Contested catch"],
    nflComp: "DeSean Jackson",
    grade: 7.9,
  },
  {
    slug: "graham-barton",
    firstName: "Graham", lastName: "Barton",
    position: "IOL", positionGroup: "OFFENSIVE_LINE",
    school: "Duke", conference: "ACC", draftYear: 2024,
    heightInches: heightToInches(6, 5), weightLbs: 313,
    actualPick: 26, actualRound: 1, actualTeamAbbr: "TB",
    age: 22.9, hometown: "Brentwood, TN",
    summary: "Smart, tough interior prospect with versatility across all three OL spots. Projected as an NFL center.",
    strengths: ["IQ", "Hand placement", "Versatility", "Anchor"],
    weaknesses: ["Arm length", "Limited LT upside", "Average power in short-yardage"],
    nflComp: "Connor McGovern",
    grade: 7.9,
  },
  {
    slug: "taliese-fuaga",
    firstName: "Taliese", lastName: "Fuaga",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Oregon State", conference: "Pac-12", draftYear: 2024,
    heightInches: heightToInches(6, 6), weightLbs: 324,
    actualPick: 14, actualRound: 1, actualTeamAbbr: "NO",
    age: 22.1, hometown: "Tacoma, WA",
    summary: "Mauler RT with plus run-game mentality. Nasty finisher with NFL starter floor.",
    strengths: ["Run game finisher", "Size and power", "Anchor", "Plus grip"],
    weaknesses: ["Hand placement inconsistent", "Struggles vs quick-twitch rushers", "RT projection likely"],
    nflComp: "Lane Johnson (lite)",
    grade: 8.0,
  },
  {
    slug: "olu-fashanu",
    firstName: "Olu", lastName: "Fashanu",
    position: "OT", positionGroup: "OFFENSIVE_LINE",
    school: "Penn State", conference: "Big Ten", draftYear: 2024,
    heightInches: heightToInches(6, 6), weightLbs: 312,
    actualPick: 11, actualRound: 1, actualTeamAbbr: "NYJ",
    age: 21.2, hometown: "Waldorf, MD",
    summary: "Smooth-moving LT with pass-pro finesse. Tools-based prospect with clear NFL LT ceiling.",
    strengths: ["Kick slide and mirror", "Pass-pro technique", "Bend"],
    weaknesses: ["Run-game assertiveness", "Average power at contact"],
    nflComp: "Duane Brown",
    grade: 8.1,
  },
  {
    slug: "troy-fautanu",
    firstName: "Troy", lastName: "Fautanu",
    position: "IOL", positionGroup: "OFFENSIVE_LINE",
    school: "Washington", conference: "Pac-12", draftYear: 2024,
    heightInches: heightToInches(6, 4), weightLbs: 317,
    actualPick: 20, actualRound: 1, actualTeamAbbr: "PIT",
    age: 23.4, hometown: "Las Vegas, NV",
    summary: "Toolsy flex piece who played LT at Washington but profiles as a dominant guard in the NFL.",
    strengths: ["Versatility", "Run-game nastiness", "Athletic profile"],
    weaknesses: ["Arm length", "OT projection limited", "Can play too hot"],
    nflComp: "Quenton Nelson (lite)",
    grade: 7.9,
  },
];
